---
version: "3"
services:
  gitlist:
    image: gitlist
    container_name: gitlist
    environment:
      - PUID=<user id>
      - PGID=<group id>
    volumes:
      - <path to repositories>:/repos
      - <path to config.ini file>:/config/config.ini
    ports:
      - 8888:80