---
version: "3"
services:
  gitlist:
    image: gitlist-lsio
    container_name: gitlist
    environment:
      - PUID=<user id>
      - PGID=<group id>
    volumes:
      - /path/repo:/repos
    ports:
      - 8888:80
